# DOXYGEN = "c:/doxygen/bin/doxygen.exe"
DOXYGEN = "C:/Archivos de programa/doxygen/bin/doxygen.exe"

all:
# USAR CON MUCHO CUIDADO, SOBREESCRIBE LOS ARCHIVOS: header.html footer.html style.css Doxyfile
#	$(DOXYGEN) -w html last_header.html last_footer.html last_style.css Doxyfile.en
	$(DOXYGEN) Doxyfile.en
# 	$(DOXYGEN) Doxyfile.es
