DOXYGEN = "c:/Archivos de programa/doxygen/bin/doxygen.exe"

all:
# USAR CON MUCHO CUIDADO, SOBREESCRIBE LOS ARCHIVOS: header.html footer.html style.css Doxyfile
#	"c:/Archivos de programa/doxygen/bin/doxygen.exe" -w html header.html footer.html style.css Doxyfile
	$(DOXYGEN) Doxyfile
