// Vaca - Visual Application Components Abstraction
// Copyright (c) 2005-2010 David Capello
//
// This file is distributed under the terms of the MIT license,
// please read LICENSE.txt for more information.

#ifndef VACA_VACA_H
#define VACA_VACA_H

#include "vaca/base.h"

#include "vaca/Anchor.h"
#include "vaca/AnchorLayout.h"
#include "vaca/Application.h"
// #include "vaca/BandedDockArea.h"
// #include "vaca/BasicDockArea.h"
#include "vaca/Bix.h"
#include "vaca/BoxConstraint.h"
#include "vaca/BoxLayout.h"
#include "vaca/Brush.h"
#include "vaca/Button.h"
#include "vaca/ButtonBase.h"
#include "vaca/CancelableEvent.h"
#include "vaca/CheckBox.h"
#include "vaca/ClientLayout.h"
#include "vaca/Clipboard.h"
#include "vaca/CloseEvent.h"
#include "vaca/Color.h"
#include "vaca/ColorDialog.h"
#include "vaca/ComboBox.h"
#include "vaca/Command.h"
#include "vaca/CommandEvent.h"
#include "vaca/CommonDialog.h"
#include "vaca/Component.h"
#include "vaca/ConditionVariable.h"
#include "vaca/Constraint.h"
#include "vaca/ConsumableEvent.h"
#include "vaca/Cursor.h"
#include "vaca/CustomButton.h"
#include "vaca/CustomLabel.h"
#include "vaca/DataGrid.h"
#include "vaca/Debug.h"
#include "vaca/Dialog.h"
// #include "vaca/DockArea.h"
// #include "vaca/DockBar.h"
// #include "vaca/DockFrame.h"
#include "vaca/DropFilesEvent.h"
#include "vaca/Enum.h"
#include "vaca/Event.h"
#include "vaca/Exception.h"
#include "vaca/FileDialog.h"
#include "vaca/FindFiles.h"
#include "vaca/FindTextDialog.h"
#include "vaca/FocusEvent.h"
#include "vaca/Font.h"
#include "vaca/FontDialog.h"
#include "vaca/Frame.h"
#include "vaca/GdiObject.h"
#include "vaca/Graphics.h"
#include "vaca/GraphicsPath.h"
#include "vaca/GroupBox.h"
#include "vaca/HttpRequest.h"
#include "vaca/Icon.h"
#include "vaca/Image.h"
#include "vaca/ImageList.h"
#include "vaca/KeyEvent.h"
#include "vaca/Keys.h"
#include "vaca/Label.h"
#include "vaca/Layout.h"
#include "vaca/LayoutEvent.h"
#include "vaca/LinkLabel.h"
#include "vaca/ListBox.h"
#include "vaca/ListColumn.h"
#include "vaca/ListItem.h"
#include "vaca/ListView.h"
#include "vaca/Mdi.h"
#include "vaca/Menu.h"
#include "vaca/MenuItemEvent.h"
#include "vaca/Message.h"
#include "vaca/MouseEvent.h"
#include "vaca/MsgBox.h"
#include "vaca/Mutex.h"
#include "vaca/NonCopyable.h"
#include "vaca/PaintEvent.h"
#include "vaca/ParseException.h"
#include "vaca/Pen.h"
#include "vaca/Point.h"
#include "vaca/PreferredSizeEvent.h"
#include "vaca/ProgressBar.h"
#include "vaca/RadioButton.h"
#include "vaca/ReBar.h"
#include "vaca/Rect.h"
#include "vaca/Referenceable.h"
#include "vaca/Region.h"
#include "vaca/Register.h"
#include "vaca/ResizeEvent.h"
#include "vaca/ResourceException.h"
#include "vaca/ResourceId.h"
#include "vaca/RichEdit.h"
#include "vaca/Scintilla.h"
#include "vaca/ScopedLock.h"
#include "vaca/ScrollEvent.h"
#include "vaca/ScrollInfo.h"
#include "vaca/ScrollableWidget.h"
#include "vaca/Separator.h"
#include "vaca/SetCursorEvent.h"
#include "vaca/SharedPtr.h"
#include "vaca/Signal.h"
#include "vaca/Size.h"
#include "vaca/Slider.h"
#include "vaca/Slot.h"
#include "vaca/SpinButton.h"
#include "vaca/Spinner.h"
#include "vaca/SplitBar.h"
#include "vaca/StatusBar.h"
#include "vaca/String.h"
#include "vaca/Style.h"
#include "vaca/System.h"
#include "vaca/Tab.h"
#include "vaca/TextEdit.h"
#include "vaca/Thread.h"
#include "vaca/TimePoint.h"
#include "vaca/Timer.h"
#include "vaca/ToggleButton.h"
#include "vaca/ToolBar.h"
#include "vaca/TreeNode.h"
#include "vaca/TreeView.h"
#include "vaca/TreeViewEvent.h"
#include "vaca/Widget.h"
#include "vaca/WidgetClass.h"
#include "vaca/WidgetHit.h"
#include "vaca/WidgetList.h"

#endif // VACA_VACA_H
