# - Find the Vaca library
#
# This module defines
#  VACA_INCLUDE_DIR, where to find Vaca/Vaca.h, etc.
#  VACA_LIBRARY, the library to link against to use Vaca.
#  VACA_FOUND, If false, do not try to use Vaca.

FIND_PATH(VACA_INCLUDE_DIR Vaca/Vaca.h)

FIND_LIBRARY(VACA_LIBRARY NAMES Vaca)

IF(VACA_INCLUDE_DIR AND VACA_LIBRARY)
   SET(VACA_FOUND TRUE)
ENDIF(VACA_INCLUDE_DIR AND VACA_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(VACA DEFAULT_MSG VACA_LIBRARY VACA_INCLUDE_DIR)

MARK_AS_ADVANCED(VACA_INCLUDE_DIR VACA_LIBRARY)
